name: Build
on:
  push:
    branches:    
      - master
jobs:
  build:
    name: Building
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: adwirawien/public-transport-information
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
