# This will trigger updating kubernetes to specified container version

name: Build and Deploy Master to Beta

on:
  push:
    branches:
      - master

jobs:
  buildPushAndDeploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@master
      
    - run: echo "VERSION=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
    - run: echo "BACKEND_URL=${{secrets.BACKEND_URL}}" >> $GITHUB_ENV
    - run: echo ${{ env.BACKEND_URL }}
    - run: echo "MAPBOX_TOKEN=${{secrets.MAPBOX_TOKEN}}" >> $GITHUB_ENV
    - run: echo "IMPRESS_RESPONSIBLE=${{secrets.IMPRESS_RESPONSIBLE}}" >> $GITHUB_ENV
    - uses: TickX/var-to-dotenv@v1.1.1
      with:
        key: 'IMPRESS_STREET'
        value: ${{secrets.IMPRESS_STREET}}
    - uses: TickX/var-to-dotenv@v1.1.1
      with:
        key: 'IMPRESS_CITY'
        value: ${{secrets.IMPRESS_CITY}}
    - uses: TickX/var-to-dotenv@v1.1.1
      with:
        key: 'IMPRESS_PHONE'
        value: ${{secrets.IMPRESS_PHONE}}
    - uses: TickX/var-to-dotenv@v1.1.1
      with:
        key: 'IMPRESS_MAIL'
        value: ${{secrets.IMPRESS_MAIL}}
    
    - name: Build and push Docker images
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@ab83648e2e224cfeeab899e23b639660765c3a89
      uses: docker/build-push-action@v1.1.1
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: ${{ secrets.DOCKER_USER }}
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.GITHUB_TOKEN }}
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: docker.pkg.github.com
        # Docker repository to tag the image with
        repository: transportflow/transportflow-web/beta
        # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
        tags: $GITHUB_SHA
        # Whether to push the image
        push: true
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: Save DigitalOcean kubeconfig
      run: doctl kubernetes cluster kubeconfig save k8s-1-16-6-do-2-fra1-1584545136798
    - name: Update deployment
      run: kubectl set image deployments/transportflow-beta transportflow-beta=docker.pkg.github.com/transportflow/transportflow-web/beta:${{ env.SHA }} -n transportflow

